curl --request POST \
  --url https://dev-ml2kljiyngr2usm8.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"nqDXexu335gaggZAg3w8mSta0iUMul2T","client_secret":"PouJdf9EFrKE2Y4c9SH6x8KH8IwIM48fTvGmcFnlK8xnyULlErJ5-Xg5egcbioZE","audience":"https://purple-viper","grant_type":"client_credentials"}'